dist: trusty
sudo: required
language: bash

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash

install:
# Let's install ansible and ansible-lint:
- sudo pip install --upgrade pip
- sudo pip install ansible ansible-lint

# Let's install terraform
- wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip -O terraform.zip
- sudo unzip terraform.zip -d /usr/local
- export PATH=/usr/local/:$PATH

# Let's install flint:
- wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip -O tflint.zip
- sudo unzip tflint.zip -d /usr/bin

script:
# Let's test packer templates
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- packer validate -var-file=packer/variables.json.example packer/immutable.json
- packer validate -var-file=packer/variables.json.example packer/ubuntu16.json

# Let's test terraform files
- touch ~/.ssh/appuser ~/.ssh/appuser.pub
- mv terraform/terraform.tfvars.example terraform/terraform.tfvars
- mv terraform/stage/terraform.tfvars.example terraform/stage/terraform.tfvars
- mv terraform/prod/terraform.tfvars.example terraform/prod/terraform.tfvars

- cd terraform/stage && terraform init -backend=false && terraform validate
- tflint
- cd ../prod && terraform init -backend=false && terraform validate
- tflint

# Let's test ansible playbooks
- cd ../../ansible
- ansible-lint playbooks/*.yml --exclude=roles/jdauphant.nginx

notifications:
  slack:
    rooms:
      secure: WSCYpNrs9m2ZFIA2Wk1eeJFfvpX4EtrD+q+tfGGgLsvqSdZXqwV3Wz4FjeJqNOYdQW3qK0QvfdKpueeeXc/Vy7++Ja3PsUbJH+2Z6VZ0M3Sv4JdeHdyDUAUY/Zm86UuT1EZ9Fnwe2nLgk2t8i9g28y7Uvl7LhXhdNryXOeSX6BS9XwBtEtIJYAyrpJppdWrePj9X/1Z5enNFWk3uF+B7CB+Jk2R1VpC1OlSSJtFBvHriYyEWfrfgjGHFFQMNy/saidwqc0EktJrGJx2QgXoW/qwjHtF5VbzxzQVib5VhzH4Em/HClqoHazlBjRh2OER5GQbMOrGJX/VGIS+XPYH3FiZIMYdbgtUZqVeniYaQrIUiHJBrI7a4QAKB3kyOl17P0x6kIuN4rFZw4kZ+ZLR6g5Uc50ax0UJTRdyfARlsnXEXOSE8A5EJ2Btmrf5ZPILFQX1DZG+AI1AkyN78txIKvxWJbIy+9LtugF1c5olcnCnPfYGoif71lLz1oXWRtgRt6cYJPlU9eBhnKCrkw6fhynupNdwB6ebkG0MVTGq2WMtKVx2BjDe/g6Vu4EfqBnWuOsoeOzjq8/gf+oxldoHqsUvLjIXVY6laM6W+BGqvwkdyJ17zFF2O/TuQxN+aeFbjZL8PqKlfj7ykAqCGtpxSrx4iNS0W9MbuvKm6rUEhhKc=
