---
- name: Deploy application
  hosts: app
  become: true
  tasks:
    - name: Clone repo
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"
      notify: Reload puma

  handlers:
  - name: Reload puma
    systemd: name=puma state=restarted
