---
- name: Install ruby & provision bundler
  hosts: all
  become: true

  tasks:
  - name: apt-get update
    apt:
      update_cache: yes

  - name: Install ruby & bundler
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
